export const countries = [
    { code: "+93", name: "Afghanistan" },
    { code: "+355", name: "Albania" },
    { code: "+213", name: "Algeria" },
    { code: "+61", name: "Australia" },
    { code: "+32", name: "Belgium" },
    { code: "+55", name: "Brazil" },
    { code: "+1", name: "Canada" },
    { code: "+86", name: "China" },
    { code: "+225", name: "Ivory Coast" },
    { code: "+20", name: "Egypt" },
    { code: "+251", name: "Ethiopia" },
    { code: "+33", name: "France" },
    { code: "+220", name: "Gambia" },
    { code: "+49", name: "Germany" },
    { code: "+30", name: "Greece" },
    { code: "+852", name: "Hong Kong" },
    { code: "+36", name: "Hungary" },
    { code: "+91", name: "India" },
    { code: "+62", name: "Indonesia" },
    { code: "+98", name: "Iran" },
    { code: "+964", name: "Iraq" },
    { code: "+353", name: "Ireland" },
    { code: "+972", name: "Israel" },
    { code: "+39", name: "Italy" },
    { code: "+81", name: "Japan" },
    { code: "+962", name: "Jordan" },
    { code: "+254", name: "Kenya" },
    { code: "+965", name: "Kuwait" },
    { code: "+961", name: "Lebanon" },
    { code: "+60", name: "Malaysia" },
    { code: "+960", name: "Maldives" },
    { code: "+52", name: "Mexico" },
    { code: "+212", name: "Morocco" },
    { code: "+95", name: "Myanmar" },
    { code: "+977", name: "Nepal" },
    { code: "+31", name: "Netherlands" },
    { code: "+64", name: "New Zealand" },
    { code: "+234", name: "Nigeria" },
    { code: "+47", name: "Norway" },
    { code: "+968", name: "Oman" },
    { code: "+92", name: "Pakistan" },
    { code: "+63", name: "Philippines" },
    { code: "+351", name: "Portugal" },
    { code: "+974", name: "Qatar" },
    { code: "+40", name: "Romania" },
    { code: "+7", name: "Russia" },
    { code: "+966", name: "Saudi Arabia" },
    { code: "+65", name: "Singapore" },
    { code: "+27", name: "South Africa" },
    { code: "+82", name: "South Korea" },
    { code: "+34", name: "Spain" },
    { code: "+94", name: "Sri Lanka" },
    { code: "+46", name: "Sweden" },
    { code: "+41", name: "Switzerland" },
    { code: "+66", name: "Thailand" },
    { code: "+216", name: "Tunisia" },
    { code: "+90", name: "Turkey" },
    { code: "+971", name: "United Arab Emirates" },
    { code: "+44", name: "United Kingdom" },
    { code: "+1", name: "United States" },
    { code: "+598", name: "Uruguay" },
    { code: "+58", name: "Venezuela" },
    { code: "+84", name: "Vietnam" },
    { code: "+260", name: "Zambia" },
    { code: "+263", name: "Zimbabwe" },
    { code: "+973", name: "Bahrain" } // Added Bahrain
].sort((a, b) => a.name.localeCompare(b.name));

export  const arabicCountries = [
        { code: "+93", name: "أفغانستان" },
        { code: "+355", name: "ألبانيا" },
        { code: "+213", name: "الجزائر" },
        { code: "+61", name: "أستراليا" },
        { code: "+32", name: "بلجيكا" },
        { code: "+55", name: "البرازيل" },
        { code: "+1", name: "كندا" },
        { code: "+86", name: "الصين" },
        { code: "+225", name: "ساحل العاج" },
        { code: "+20", name: "مصر" },
        { code: "+251", name: "إثيوبيا" },
        { code: "+33", name: "فرنسا" },
        { code: "+220", name: "غامبيا" },
        { code: "+49", name: "ألمانيا" },
        { code: "+30", name: "اليونان" },
        { code: "+852", name: "هونغ كونغ" },
        { code: "+36", name: "هنغاريا" },
        { code: "+91", name: "الهند" },
        { code: "+62", name: "إندونيسيا" },
        { code: "+98", name: "إيران" },
        { code: "+964", name: "العراق" },
        { code: "+353", name: "أيرلندا" },
        { code: "+972", name: "إسرائيل" },
        { code: "+39", name: "إيطاليا" },
        { code: "+81", name: "اليابان" },
        { code: "+962", name: "الأردن" },
        { code: "+254", name: "كينيا" },
        { code: "+965", name: "الكويت" },
        { code: "+961", name: "لبنان" },
        { code: "+60", name: "ماليزيا" },
        { code: "+960", name: "المالديف" },
        { code: "+52", name: "المكسيك" },
        { code: "+212", name: "المغرب" },
        { code: "+95", name: "ميانمار" },
        { code: "+977", name: "نيبال" },
        { code: "+31", name: "هولندا" },
        { code: "+64", name: "نيوزيلندا" },
        { code: "+234", name: "نيجيريا" },
        { code: "+47", name: "النرويج" },
        { code: "+968", name: "عمان" },
        { code: "+92", name: "باكستان" },
        { code: "+63", name: "الفلبين" },
        { code: "+351", name: "البرتغال" },
        { code: "+974", name: "قطر" },
        { code: "+40", name: "رومانيا" },
        { code: "+7", name: "روسيا" },
        { code: "+966", name: "المملكة العربية السعودية" },
        { code: "+65", name: "سنغافورة" },
        { code: "+27", name: "جنوب أفريقيا" },
        { code: "+82", name: "كوريا الجنوبية" },
        { code: "+34", name: "إسبانيا" },
        { code: "+94", name: "سريلانكا" },
        { code: "+46", name: "السويد" },
        { code: "+41", name: "سويسرا" },
        { code: "+66", name: "تايلاند" },
        { code: "+216", name: "تونس" },
        { code: "+90", name: "تركيا" },
        { code: "+971", name: "الإمارات العربية المتحدة" },
        { code: "+44", name: "المملكة المتحدة" },
        { code: "+1", name: "الولايات المتحدة" },
        { code: "+598", name: "أوروغواي" },
        { code: "+58", name: "فنزويلا" },
        { code: "+84", name: "فيتنام" },
        { code: "+260", name: "زامبيا" },
        { code: "+263", name: "زيمبابوي" },
        { code: "+973", name: "البحرين" } // Added Bahrain
    ].sort((a, b) => a.name.localeCompare(b.name));
    